### ISSUE TITLE
some behaviors broken

### ISSUE THREAD

**Issue by macMikey** [macMikey/tmc3#4]
Some behaviors broken
- [X] toolbar (wrong library assigned)

### Not inheriting masterBehavior and running the onDesktop() function:
- [ ] mobile scroller
- [ ] vertical template table (mobile scroller lib)
- [ ] horizontal template table (mobile scroller lib)
- [ ] mobile browser

**Comment by macMikey** [comment]
Problem seems to be in **before mouseMove** in the scrollerlib calling **onDesktop()**

**Comment by macMikey** [comment]
[Bug report](quality.livecode.com/show_bug.cgi?id=23528)

**Comment by macMikey** [comment]
Bug confirmed by Panos. id 23528
Also suggests a workaround,
adding to *app.yml* in the *behaviors* section:
`- filename: ./behaviors/tmc3/libs/tmc3_MasterBehavior.livecodescript`

**Comment by macMikey** [comment]
However, because of the nesting of behaviors, naming everything and getting the order right seems like it works better
```yml
  - filename: ./behaviors/tmc3/libs/tmc3_MasterBehavior.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_button_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_card_resize_behavior.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_colorize.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_field_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_mobile_browser_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_mobile_player_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_mobile_scroller_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_mobile_text_input_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_navbar_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_page_control_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_progressbar_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_region_selection_monitor.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_segmented_control_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_simple_chart_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_simple_gauge_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_simple_table_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_slider_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_stepper_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_swipe_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_switch_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_tab_bar_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_template_table_lib.livecodescript
  - filename: ./behaviors/tmc3/libs/tmc3_toolbar_lib.livecodescript
  - folder: ./behaviors
```
